package main

// limen --import: read the nginx configuration the machine had before
// limen, and bring into the model what can be brought faithfully.
//
// Without --write it only prints the plan: what would be created, what
// is left out and why, and what is dropped on the way. Nothing is ever
// overwritten, and a server whose guard cannot be kept is not imported.

import (
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/ostap-mykhaylyak/limen/internal/importer"
	"github.com/ostap-mykhaylyak/limen/internal/model"
	"github.com/ostap-mykhaylyak/limen/internal/nginx"
	"github.com/ostap-mykhaylyak/limen/internal/paths"
	"github.com/ostap-mykhaylyak/limen/internal/store"
)

func runImport(args []string, out io.Writer) error {
	fs := flag.NewFlagSet("limen --import", flag.ContinueOnError)
	from := fs.String("from", "", "the nginx.conf to import (default: the newest backup made by --init)")
	write := fs.Bool("write", false, "create the documents and apply them; without it, only show the plan")
	if err := fs.Parse(args); err != nil {
		if errors.Is(err, flag.ErrHelp) {
			return nil
		}
		return err
	}

	src, rebase, err := importSource(*from)
	if err != nil {
		return err
	}
	s, err := store.Open(store.DefaultDirs())
	if err != nil {
		return err
	}
	return importFrom(s, src, rebase, *write, out, paths.CertsDir, applier(s))
}

// importSource finds the configuration to import and how to read its
// absolute includes: a backup of /etc/nginx still says /etc/nginx.
func importSource(from string) (string, func(string) string, error) {
	rebaseTo := func(dir string) func(string) string {
		return func(p string) string {
			if rest, ok := strings.CutPrefix(p, paths.NginxConfDir+"/"); ok {
				return filepath.Join(dir, rest)
			}
			return p
		}
	}
	if from != "" {
		dir := filepath.Dir(from)
		if dir == paths.NginxConfDir {
			return from, nil, nil
		}
		return from, rebaseTo(dir), nil
	}

	if backups, _ := filepath.Glob(filepath.Join(paths.BackupDir, "nginx-*", "nginx.conf")); len(backups) > 0 {
		sort.Strings(backups)
		newest := backups[len(backups)-1]
		return newest, rebaseTo(filepath.Dir(newest)), nil
	}
	before := filepath.Join(paths.NginxConfDir, "nginx.conf.before-limen")
	if _, err := os.Stat(before); err == nil {
		return before, nil, nil
	}
	if b, err := os.ReadFile(paths.NginxConfFile); err == nil && !strings.Contains(string(b), "Generated by limen") {
		return paths.NginxConfFile, nil, nil
	}
	return "", nil, fmt.Errorf("nothing to import: no backup in %s and %s is already limen's; pass --from", paths.BackupDir, paths.NginxConfFile)
}

// importFrom does the work; the pieces that touch the machine come in
// as arguments, so that it can be tested on a temporary tree.
func importFrom(s *store.Store, src string, rebase func(string) string, write bool, out io.Writer,
	certsDir string, apply func(bool) (nginx.Result, error)) error {

	parser := &importer.Parser{Rebase: rebase}
	top, err := parser.ParseFile(src)
	if err != nil {
		return fmt.Errorf("read %s: %w", src, err)
	}
	read := func(p string) ([]byte, error) {
		if rebase != nil {
			p = rebase(p)
		}
		return os.ReadFile(p)
	}
	plan := importer.Build(top, importer.Options{
		Exists: func(kind model.Kind, name string) bool {
			_, err := s.Get(kind, name)
			return err == nil
		},
		ReadFile: read,
	})

	fmt.Fprintf(out, "Reading %s\n\n", src)
	if write {
		fmt.Fprintln(out, "Importing:")
	} else {
		fmt.Fprintln(out, "Would import:")
	}
	if len(plan.Docs) == 0 {
		fmt.Fprintln(out, "  nothing")
	}
	for _, d := range plan.Docs {
		fmt.Fprintf(out, "  %-12s %-32s %s\n", d.Header().Kind, d.Header().Name, describe(d))
	}
	if len(plan.Certs) > 0 {
		fmt.Fprintln(out, "\nCertificates to copy into limen:")
		for _, c := range plan.Certs {
			fmt.Fprintf(out, "  %-32s from %s\n", c.Name, c.Chain)
		}
		fmt.Fprintln(out, "  (renewals by certbot will not reach the copies: limen takes renewals over with ACME)")
	}
	section(out, "Left out", plan.Skipped)
	section(out, "Notes", append(parser.Notes, plan.Notes...))

	if !write {
		fmt.Fprintln(out, "\nNothing was written. Run again with --write to import.")
		return nil
	}

	fmt.Fprintln(out)
	for _, c := range plan.Certs {
		if err := copyCert(c, certsDir, read); err != nil {
			fmt.Fprintf(out, "certificate %s: %v (the host is served over plain HTTP until it has one)\n", c.Name, err)
		}
	}

	ch := store.Change{Author: operator(), Source: "import", Note: "imported from " + src}
	created, failed := 0, 0
	err = s.Locked(func() error {
		for _, d := range plan.Docs {
			if _, err := s.Put(d, ch); err != nil {
				fmt.Fprintf(out, "not imported: %v\n", err)
				failed++
				continue
			}
			created++
		}
		return nil
	})
	if err != nil {
		return err
	}
	fmt.Fprintf(out, "%d document(s) imported, %d refused by the model\n", created, failed)
	if created == 0 || apply == nil {
		return nil
	}
	res, err := apply(false)
	if err != nil {
		return fmt.Errorf("the documents are saved, but nginx was not updated: %w", err)
	}
	(&cli{out: out}).printApply(res)
	return nil
}

func section(out io.Writer, title string, lines []string) {
	if len(lines) == 0 {
		return
	}
	fmt.Fprintf(out, "\n%s:\n", title)
	for _, l := range lines {
		fmt.Fprintf(out, "  - %s\n", l)
	}
}

func describe(d model.Document) string {
	switch v := d.(type) {
	case *model.ProxyHost:
		s := strings.Join(v.Domains, ",") + " -> " + v.Forward.String()
		if v.TLS.Certificate != "" {
			s += " (TLS"
			if v.TLS.ForceHTTPS {
				s += ", forced"
			}
			s += ")"
		}
		if v.AccessList != "" {
			s += " guarded by " + v.AccessList
		}
		return s
	case *model.Redirect:
		return fmt.Sprintf("%s -> %d %s", strings.Join(v.Domains, ","), v.Code, v.Target)
	case *model.Stream:
		return fmt.Sprintf("%d/%s -> %s", v.Listen, strings.Join(v.Protocols, ","), v.Forward)
	case *model.AccessList:
		return fmt.Sprintf("%d user(s), %d rule(s)", len(v.Users), len(v.Rules))
	}
	return ""
}

// copyCert copies a certificate and its key into limen's store. An
// existing certificate of the same name is left alone.
func copyCert(c importer.CertCopy, certsDir string, read func(string) ([]byte, error)) error {
	dir := filepath.Join(certsDir, c.Name)
	if _, err := os.Stat(filepath.Join(dir, "fullchain.pem")); err == nil {
		return nil
	}
	chain, err := read(c.Chain)
	if err != nil {
		return err
	}
	key, err := read(c.Key)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(dir, "fullchain.pem"), chain, 0o600); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, "privkey.pem"), key, 0o600)
}
