package nginx

// mimeTypes ships with limen, so that the configuration does not depend
// on the mime.types file of the distribution (which limen does not own
// and a package upgrade may move). It covers what a proxy actually
// serves itself — error pages, and assets when a backend omits the
// header — not every type there is.
const mimeTypes = `# MIME types. Generated by limen.
types {
    text/html                                        html htm shtml;
    text/css                                         css;
    text/xml                                         xml;
    text/plain                                       txt;
    text/csv                                         csv;
    text/markdown                                    md;
    text/calendar                                    ics;
    text/javascript                                  js mjs;
    application/json                                 json map;
    application/manifest+json                        webmanifest;
    application/ld+json                              jsonld;
    application/xml                                  rss atom;
    application/pdf                                  pdf;
    application/zip                                  zip;
    application/gzip                                 gz;
    application/x-tar                                tar;
    application/x-7z-compressed                      7z;
    application/wasm                                 wasm;
    application/octet-stream                         bin exe dll deb iso img msi dmg;
    application/msword                               doc;
    application/vnd.openxmlformats-officedocument.wordprocessingml.document    docx;
    application/vnd.ms-excel                         xls;
    application/vnd.openxmlformats-officedocument.spreadsheetml.sheet          xlsx;
    application/vnd.ms-powerpoint                    ppt;
    application/vnd.openxmlformats-officedocument.presentationml.presentation  pptx;
    application/vnd.oasis.opendocument.text          odt;
    application/vnd.oasis.opendocument.spreadsheet   ods;
    application/rtf                                  rtf;
    image/png                                        png;
    image/jpeg                                       jpeg jpg;
    image/gif                                        gif;
    image/webp                                       webp;
    image/avif                                       avif;
    image/svg+xml                                    svg svgz;
    image/x-icon                                     ico;
    image/bmp                                        bmp;
    image/tiff                                       tif tiff;
    font/woff                                        woff;
    font/woff2                                       woff2;
    font/ttf                                         ttf;
    font/otf                                         otf;
    application/vnd.ms-fontobject                    eot;
    audio/mpeg                                       mp3;
    audio/ogg                                        ogg oga;
    audio/wav                                        wav;
    audio/aac                                        aac;
    audio/flac                                       flac;
    video/mp4                                        mp4 m4v;
    video/webm                                       webm;
    video/ogg                                        ogv;
    video/quicktime                                  mov;
    video/x-msvideo                                  avi;
    application/vnd.apple.mpegurl                    m3u8;
    video/mp2t                                       ts;
}
`
